name: Tenable IaC Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

  steps:
  - name: Checkout
    uses: actions/checkout@v3
  - name: Scan IaC with Tenable Cloud Security
    uses: ermetic/actions/iac/scan@v1
    with:
      api-token: ${{secrets.TENABLE_API_TOKEN}}
      api-url: https://us.app.ermetic.com
